# Generated by Django 5.0.6 on 2024-05-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='None', max_length=100),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
